### ISSUE TITLE
Memory consumption increases in a linear manner with the same workload

### ISSUE THREAD

**Issue by kartoffelsup** [brettwooldridge/NuProcess#127]
Hi,

thank you for creating NuProcess :)

we wanted to use NuProcess to ping many hosts in a scheduled task but we ran into an issue where the memory usage just kept increasing. I've reproduced this with a minimal example below:

![grafik](https://user-images.githubusercontent.com/1819197/120003415-0142e580-bfd6-11eb-9541-db052b8f14ca.png)

I've setup two test runners in AWS ECS Fargate.

[JavaProcessTest.java](https://gist.github.com/kartoffelsup/10c6283e5505c57f5f6e1e0b4b43336c)

[NuProcesstest.java](https://gist.github.com/kartoffelsup/4c12b0be9609ec90e1fef6a3c861ae3e)

Are we using NuProcess the wrong way or is this a bug?

Any help is appreciated :)

**Comment by bturner** [comment]
What you're seeing is the illusion of increased memory usage.

The sample app isn't triggering any sort of GC, so until the collector decides to step in (which, so long as it has heap headroom, it won't), garbage is allowed to build up. Pair that with the fact that sample produces quite a lot of garbage (because it allocates a new `byte[]` each time it wants to copy data out of a `ByteBuffer`) and you get a nice, steady climb. If you add a `System.gc()` before you write the sizes after `join`ing all your `Future`s you'll get a perfectly flat line. I've had that running for the last 3 hours and the memory numbers haven't changed at all.

In practice, if you're going to translate from `ByteBuffer` to `String`, you probably want to use something like `NuAbstractCharsetHandler` to help. That's going to handle split multibyte characters correctly (which the sample code currently wouldn't; of course, if it's only dealing with ASCII output that's not a concern), and it's also going to reuse buffers between callbacks, which reduces allocation churn. (You can, of course, write your own decoding/buffering; I'm just pointing out  an existing helper.)

There's a second bug in the sample, just FYI, in how `append` deals with `closed`. `closed` being `true` _does not_ mean the `buffer` is empty; you can get data on the final callback (and often do). The current handling means the sample doesn't necessarily process all the output. Replacing the `if (!closed)` with `if (buffer.hasRemaining())` would fix that.

**Comment by kartoffelsup** [comment]
Hi,

thanks for the explanation and the tips :) I've reproduced what you described, sorry for wasting your time with this non-bug. 

![image (2)](https://user-images.githubusercontent.com/1819197/120066919-29375500-c079-11eb-80d7-9f1408b56f08.png)
