### ISSUE TITLE
How to use error streams in nuProcess builder?

### ISSUE THREAD

**Issue by VEDANTDOKANIA** [brettwooldridge/NuProcess#139]
As in java process builder we have something like redirect error stream and we can change the option to get error stream output also . Do we have something same in nuProcess builder , As i am trying to run the  command - fping -c 3 -t 1000 -q host.ip" and its output is redirected in the error stream , so how to take that output ?

**Comment by bturner** [comment]
@VEDANTDOKANIA, I assume you found a way forward? If you want to consume `stderr`, that output will be delivered to `onStderr` on your `NuProcessHandler`. There currently isn't anything built into NuProcess for redirecting `stderr` to `stdout` so that output will be delivered to `onStdout` instead, but you could implement your handler to call `onStdout` from `onStderr`.
