### ISSUE TITLE
current working directory (cwd) support

### ISSUE THREAD

**Issue by okapies** [brettwooldridge/NuProcess#27]
The [README](https://github.com/brettwooldridge/NuProcess/blob/c3738ae5dcb862f3fb4c2621ef36440087146172/README.md#limitations) states that *"NuProcess does not currently permit setting an alternate current working directory (cwd) for the child process."*

Why does this limitation exist, and will be solved in near future?

**Comment by brettwooldridge** [comment]
This limitation exists because NuProcess calls ``posix_spawnp()`` on Linux to launch a process.  A spawned process always inherits its parent's cwd.

If NuProcess were to, for example, change the cwd before spawning then the new process would use that cwd.  The problem is that a cwd change is *process-wide*, and all threads in the process are affected.

Even if NuProcess changed the cwd, spawned your process, then quickly changed the cwd back, there is still a short window of time when other threads doing things like ``new File("xyz")`` will be opening and creating files in incorrect locations.  This can cause complete havoc.

The way that the JDK itself works around this is by "double-forking".  First it forks the JVM itself.  The forked JVM then changes the directory to the one the user specified (the parent JVM process is unaffected).  Then the forked JVM spawned your specified process, which inherits the correct cwd.

Unfortunately, because NuProcess does not use native code of its own (we use JNA to access native functionality), this "double-fork" trick is not available to us.  At least we have not found a way to do it.

**Comment by okapies** [comment]
Thanks for the detailed explanation! I found the trick of the JDK you mentioned, in the [OpenJDK's source code](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/eb78b3fdf14e/src/solaris/native/java/lang/childproc.c#l313).

IMHO, It seems it is not so difficult to exploit the "double-fork" trick by implementing a small *shared library* accessed via JNI and [embedding in the jar](https://github.com/timmattison/jayuda/blob/master/src/com/timmattison/jayuda/jarloader/LoadLibraryFromJar.java). Can it be a solution for the issue?

**Comment by brettwooldridge** [comment]
@okapies Yes, of course a JNI solution could solve the issue.  I have thought it about it in the past.  But because NuProcess works for the environment in which I needed it, I haven't spent time investigating the JNI solution.

One disadvantage of JNI would be compilng versions of the shared library for different architectures.  For example, I was able to run NuProcess on Raspberry Pi with no modifications.  However, if there was a JNI library, I would have needed to compile a version of the shared library for ARM.

However, I would certainly welcome any pull requests.  Such an implementation should probably throw an exception if ``setWorkingDirectory()`` is called on an unsupported architecture.

**Comment by okapies** [comment]
あらららw そうです、東京在住の日本人です。あと、プロフィールを拝見したのですが HikariCP の作者さんだったのですね…！

And ok, I fully understand the situation. I'll try implementing it ... if time permits (I'm implementing [non-blocking process library](https://github.com/okapies/rx-process) based on NuProcess and RxJava). Thanks for your great in-depth comments!

**Comment by bgertzfield** [comment]
It looks like Java itself has the same issue when using `posix_spawnp()` from its own `ProcessBuilder` API. The JRE ships a native helper tool called `jspawnhelper` which supports setting `cwd` among other things:

http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/solaris/native/java/lang/jspawnhelper.c

I bet NuProcess could invoke the exact same tool; you just have to encode the environment, CWD, args, etc. appropriately and pass them over a pipe whose FDs you pass in `argv[1]`.

**Comment by bgertzfield** [comment]
Also, on OS X, you can invoke syscall 348 (`SYS___pthread_chdir`) to set the current working directory of the calling thread, then set it back after invoking `posix_spawnp()`.

Of course, that's not portable to Linux. I found some references suggesting the Linux-specific `unshare(CLONE_FS)` allows a multithreaded process on Linux to have per-thread current working directories, but I haven't tested that.

**Comment by bgertzfield** [comment]
Here's a proof-of-concept which works on OS X to use `SYS___pthread_chdir` to change the directory before calling `posix_spawnp()`. I included some tests to show it works.

https://github.com/brettwooldridge/NuProcess/compare/master...bgertzfield:directory?expand=1

I used `Path` from Java 7, so it'll probably have to be backported to 6.

**Comment by bhamiltoncx** [comment]
I finished this feature up and tested it on Linux, Mac, and Windows:

https://github.com/bhamiltoncx/NuProcess/commit/446249cf0dacec8ce9855d4a76843e640c1d3365

I'll send a pull request shortly (although I don't know about Java 6 compatibility).

**Comment by bhamiltoncx** [comment]
Hm, I suppose it's not possible to stack pull requests. Well, here it is anyway: https://github.com/bhamiltoncx/NuProcess/pull/1

**Comment by okapies** [comment]
:+1: :+1: :+1:

**Comment by brettwooldridge** [comment]
Re: Java 6, meh.  Users can stick to the 0.9.x releases if they want Java 6.  Java 6 is well past end of life and end of support.  Even Java 7 is technically [past end of support](http://www.oracle.com/technetwork/java/javase/downloads/eol-135779.html).

I won't lose any sleep over declaring Java 7 as the base supported version.

**Comment by bhamiltoncx** [comment]
Rebased on master, proper pull request: https://github.com/brettwooldridge/NuProcess/pull/32

**Comment by brettwooldridge** [comment]
This is fixed in the current version, 1.0.0, available in the maven central repository.

**Comment by bhamiltoncx** [comment]
I think the cwd feature might not have been merged yet, unless I missed it: https://github.com/brettwooldridge/NuProcess/pull/32

**Comment by minecrafter** [comment]
@brettwooldridge Can confirm that cwd support is absent in 1.0.0 in Central.

I've been waiting for this support to come to NuProcess for a while now, and I'm very happy it's in now and I'd like to utilize it.

**Comment by brettwooldridge** [comment]
@minecrafter I have just published ver 1.0.3 to the maven central repository.

**Comment by minecrafter** [comment]
Thanks!
