### ISSUE TITLE
Thoughts on using netty ByteBuf over java ByteBuffer

### ISSUE THREAD

**Issue by cdancy** [brettwooldridge/NuProcess#68]
Netty allows for the library to be used in a generic fashion rather than for standing up a server/client. As such one could use their ByteBuf as a replacement for java's ByteBuffer for all the reasons documented in the link. Something we could leverage here? Thoughts?

https://github.com/netty/netty/wiki/Using-as-a-generic-library

**Comment by brettwooldridge** [comment]
@cdancy Thanks for using NuProcess.

There are a number of major projects that use NuProcess that are fairly adamant about not pulling in other dependencies.

There are many alternatives to ByteBuffer out there, including netty's and [square/okio](https://github.com/square/okio).  The number of users who use square/okio is probably much greater than those who use netty as a generic library, so arguably that would be the better choice.

However, NuProcess' relatively simple API and interaction model simply doesn't impose much burden on the user with respect to ByteBuffer interaction, and none of the GC problems that the Netty project encountered have surfaced for users of NuProcess, so it is difficult to find justification to switch.

The ByteBuffer instances in NuProcess essentially live for the life of a process, so the amount of allocation and GC is extremely low.  With the performance issue off the table, that leaves only the somewhat clunky interaction model of ByteBuffer -- with ``flip()`` and whotnot -- which is not *so* clunky because of our relatively light interaction model and the fact that NuProcess [does half of the flips](https://github.com/brettwooldridge/NuProcess/blob/11ab9ae980a80607034ff3cdc94c52a593a098aa/src/main/java/com/zaxxer/nuprocess/windows/WindowsProcess.java#L419) for the user anyway.

**Comment by cdancy** [comment]
Fair enough and thanks for chiming in. Yes I like the library as it makes working with processes stupid simple and efficient.

Having actually worked with netty/okio previously, for nio related use-cases, I can say (which I _believe_ is well known at this point) that while okio is _easier_ to plugin and use netty's `ByteBuf` is just more efficient and performant all around. Though I agree with your statement in that it just may not be worth it.
